# Generated by Django 4.1.7 on 2023-03-02 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=100, verbose_name='Nome da Receita')),
                ('ingrediente', models.TextField(verbose_name='Igredientes')),
                ('modo_preparo', models.TextField(verbose_name='Modo de Preparo')),
                ('tempo_preparo', models.IntegerField(verbose_name='Tempo ded Preparo')),
                ('rendimento', models.CharField(max_length=100, verbose_name='Redimento')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('date_receita', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data da Receita')),
            ],
        ),
    ]
