# Generated by Django 4.1.7 on 2023-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='ingrediente',
            field=models.TextField(verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='rendimento',
            field=models.CharField(max_length=100, verbose_name='Rendimento'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='tempo_preparo',
            field=models.IntegerField(verbose_name='Tempo de Preparo'),
        ),
    ]
