# Generated by Django 4.1.7 on 2023-03-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('receitas', '0002_alter_receitas_ingrediente_alter_receitas_rendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
            preserve_default=False,
        ),
    ]
