# Generated by Django 4.1.7 on 2023-03-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receitas_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
