# Generated by Django 4.1.7 on 2023-03-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receitas_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
